server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            # '*' with allowCredentials is invalid for allowedOrigins.
            # Use allowedOriginPatterns instead.
            allowedOriginPatterns: ${CORS_ALLOWED_ORIGIN_PATTERNS:*}
            allowedMethods: [GET,POST,PUT,PATCH,DELETE,OPTIONS]
            allowedHeaders: ['*']
            allowCredentials: true
      routes:
        

        # Auth Service
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/swagger-ui/(?<segment>.*), /swagger-ui/${segment}
            - RewritePath=/auth/v3/api-docs(?<rest>/.*)?, /v3/api-docs${rest}
        # Auth Swagger
        - id: auth-swagger
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/swagger-ui/**,/auth/v3/api-docs/**,/auth/v3/api-docs.yaml
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}
        # Members (account) endpoints → Auth Service
        - id: auth-members
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/members/**
        

        # Routine Swagger UI helper (inject configUrl)
        - id: routine-swagger-ui
          order: -10
          uri: http://routine-service:8082
          predicates:
            - Path=/routines/swagger-ui/index.html
          filters:
            - AddRequestParameter=url,/routines/v3/api-docs
            - RewritePath=/routines/(?<segment>.*), /${segment}
        # Routine Swagger
        - id: routine-swagger
          order: -10
          uri: http://routine-service:8082
          predicates:
            - Path=/routines/swagger-ui/**,/routines/v3/api-docs/**,/routines/v3/api-docs.yaml
          filters:
            - RewritePath=/routines/(?<segment>.*), /${segment}
        # Handle root /v3/api-docs/swagger-config when UI origin is /routines/swagger-ui
        - id: routine-swagger-config-root
          order: -30
          uri: http://routine-service:8082
          predicates:
            - Path=/v3/api-docs/swagger-config
            - Header=Referer, .*/routines/swagger-ui.*
        # Handle root /v3/api-docs when UI origin is /routines/swagger-ui
        - id: routine-openapi-root
          order: -30
          uri: http://routine-service:8082
          predicates:
            - Path=/v3/api-docs
            - Header=Referer, .*/routines/swagger-ui.*
        # Routine Swagger static assets under /routines/*.css|js|png -> /swagger-ui/*
        - id: routine-swagger-assets
          order: -20
          uri: http://routine-service:8082
          predicates:
            - Path=/routines/*.css,/routines/*.js,/routines/*.png
          filters:
            - RewritePath=/routines/(?<asset>.*), /swagger-ui/${asset}
        # Routine Swagger entry (direct path + url param)
        - id: routine-swagger-entry
          order: -20
          uri: http://routine-service:8082
          predicates:
            - Path=/routines/swagger-ui,/routines/swagger-ui/
          filters:
            - SetPath=/swagger-ui/index.html
            - AddRequestParameter=url,/routines/v3/api-docs
        # Routine Service
        - id: routine-service
          order: 0
          uri: lb://ROUTINE-SERVICE
          predicates:
            - Path=/routines/**
          filters:
            - RewritePath=/routines/swagger-ui/(?<segment>.*), /swagger-ui/${segment}
            - RewritePath=/routines/v3/api-docs(?<rest>/.*)?, /v3/api-docs${rest}
        

        # Comment Swagger UI helper
        - id: comment-swagger-ui
          order: -10
          uri: http://comment-service:8083
          predicates:
            - Path=/comments/swagger-ui/index.html
          filters:
            - AddRequestParameter=url,/comments/v3/api-docs
            - RewritePath=/comments/(?<segment>.*), /${segment}
        # Comment Swagger
        - id: comment-swagger
          order: -10
          uri: http://comment-service:8083
          predicates:
            - Path=/comments/swagger-ui/**,/comments/v3/api-docs/**,/comments/v3/api-docs.yaml
          filters:
            - RewritePath=/comments/(?<segment>.*), /${segment}
        # Comment root swagger-config/openapi with Referer guard
        - id: comment-swagger-config-root
          order: -30
          uri: http://comment-service:8083
          predicates:
            - Path=/v3/api-docs/swagger-config
            - Header=Referer, .*/comments/swagger-ui.*
        - id: comment-openapi-root
          order: -30
          uri: http://comment-service:8083
          predicates:
            - Path=/v3/api-docs
            - Header=Referer, .*/comments/swagger-ui.*
        # Comment Swagger static assets
        - id: comment-swagger-assets
          order: -20
          uri: http://comment-service:8083
          predicates:
            - Path=/comments/*.css,/comments/*.js,/comments/*.png
          filters:
            - RewritePath=/comments/(?<asset>.*), /swagger-ui/${asset}
        # Comment Swagger entry
        - id: comment-swagger-entry
          order: -20
          uri: http://comment-service:8083
          predicates:
            - Path=/comments/swagger-ui,/comments/swagger-ui/
          filters:
            - SetPath=/swagger-ui/index.html
            - AddRequestParameter=url,/comments/v3/api-docs
        # Comment Service
        - id: comment-service
          order: 0
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comments/**
          filters:
            - RewritePath=/comments/swagger-ui/(?<segment>.*), /swagger-ui/${segment}
            - RewritePath=/comments/v3/api-docs(?<rest>/.*)?, /v3/api-docs${rest}
        

        # Like Swagger UI helper
        - id: like-swagger-ui
          order: -10
          uri: http://like-service:8084
          predicates:
            - Path=/likes/swagger-ui/index.html
          filters:
            - AddRequestParameter=url,/likes/v3/api-docs
            - RewritePath=/likes/(?<segment>.*), /${segment}
        # Like Swagger
        - id: like-swagger
          order: -10
          uri: http://like-service:8084
          predicates:
            - Path=/likes/swagger-ui/**,/likes/v3/api-docs/**,/likes/v3/api-docs.yaml
          filters:
            - RewritePath=/likes/(?<segment>.*), /${segment}
        # Like root swagger-config/openapi with Referer guard
        - id: like-swagger-config-root
          order: -30
          uri: http://like-service:8084
          predicates:
            - Path=/v3/api-docs/swagger-config
            - Header=Referer, .*/likes/swagger-ui.*
        - id: like-openapi-root
          order: -30
          uri: http://like-service:8084
          predicates:
            - Path=/v3/api-docs
            - Header=Referer, .*/likes/swagger-ui.*
        # Like Swagger static assets
        - id: like-swagger-assets
          order: -20
          uri: http://like-service:8084
          predicates:
            - Path=/likes/*.css,/likes/*.js,/likes/*.png
          filters:
            - RewritePath=/likes/(?<asset>.*), /swagger-ui/${asset}
        # Like Swagger entry
        - id: like-swagger-entry
          order: -20
          uri: http://like-service:8084
          predicates:
            - Path=/likes/swagger-ui,/likes/swagger-ui/
          filters:
            - SetPath=/swagger-ui/index.html
            - AddRequestParameter=url,/likes/v3/api-docs
        # Like Service
        - id: like-service
          order: 0
          uri: lb://LIKE-SERVICE
          predicates:
            - Path=/likes/**
          filters:
            - RewritePath=/likes/swagger-ui/(?<segment>.*), /swagger-ui/${segment}
            - RewritePath=/likes/v3/api-docs(?<rest>/.*)?, /v3/api-docs${rest}
        

        # Stats Swagger UI helper
        - id: stats-swagger-ui
          order: -10
          uri: http://stats-service:8085
          predicates:
            - Path=/stats/swagger-ui/index.html
          filters:
            - AddRequestParameter=url,/stats/v3/api-docs
            - RewritePath=/stats/(?<segment>.*), /${segment}
        # Stats Swagger
        - id: stats-swagger
          order: -10
          uri: http://stats-service:8085
          predicates:
            - Path=/stats/swagger-ui/**,/stats/v3/api-docs/**,/stats/v3/api-docs.yaml
          filters:
            - RewritePath=/stats/(?<segment>.*), /${segment}
        # Stats root swagger-config/openapi with Referer guard
        - id: stats-swagger-config-root
          order: -30
          uri: http://stats-service:8085
          predicates:
            - Path=/v3/api-docs/swagger-config
            - Header=Referer, .*/stats/swagger-ui.*
        - id: stats-openapi-root
          order: -30
          uri: http://stats-service:8085
          predicates:
            - Path=/v3/api-docs
            - Header=Referer, .*/stats/swagger-ui.*
        # Stats Swagger static assets
        - id: stats-swagger-assets
          order: -20
          uri: http://stats-service:8085
          predicates:
            - Path=/stats/*.css,/stats/*.js,/stats/*.png
          filters:
            - RewritePath=/stats/(?<asset>.*), /swagger-ui/${asset}
        # Stats Swagger entry
        - id: stats-swagger-entry
          order: -20
          uri: http://stats-service:8085
          predicates:
            - Path=/stats/swagger-ui,/stats/swagger-ui/
          filters:
            - SetPath=/swagger-ui/index.html
            - AddRequestParameter=url,/stats/v3/api-docs
        # Stats Service
        - id: stats-service
          order: 0
          uri: lb://STATS-SERVICE
          predicates:
            - Path=/stats/**
          filters:
            - RewritePath=/stats/swagger-ui/(?<segment>.*), /swagger-ui/${segment}
            - RewritePath=/stats/v3/api-docs(?<rest>/.*)?, /v3/api-docs${rest}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

# JWT Secret (env: JWT_SECRET 로 주입, 기본값은 개발용)
jwt:
  secret: ${JWT_SECRET:change-me-please-use-32-bytes-minimum-xxxxxxxxxxxxxxxx}
