name: ci-cd

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - name: Build microservices
        run: |
          for s in eureka-server gateway auth-service routine-service comment-service like-service stats-service; do \
            (cd health-routine-tracker/$s && ./gradlew clean bootJar -x test || gradle clean bootJar -x test); \
          done
      - name: Docker build (local)
        run: |
          docker compose -f health-routine-tracker/docker-compose-prod.yml build
      # Add deploy steps using SSH/compose as needed (requires secrets)
      # - name: Deploy on EC2
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ec2-user
      #     key: ${{ secrets.EC2_KEY }}
      #     script: |
      #       cd /home/ec2-user/app
      #       docker compose -f docker-compose-prod.yml up -d --build

