# Health Routine Tracker 백엔드 애플리케이션 설정 파일
# 
# 이 파일은 Spring Boot 애플리케이션의 주요 설정을 정의합니다.
# 데이터베이스 연결, JPA 설정, 보안 설정, CORS 설정 등을 포함합니다.
# 
# 주요 설정 항목:
# - 데이터베이스: MariaDB 연결 설정
# - JPA/Hibernate: 엔티티 매핑 및 SQL 로깅 설정
# - 보안: JWT 토큰 설정 및 기본 인증 정보
# - CORS: 프론트엔드 도메인 허용 설정
# - 서버: 포트 및 컨텍스트 경로 설정
# - 모니터링: Actuator 엔드포인트 설정
# - API 문서: Swagger/OpenAPI 설정
#
# @author Health Routine Tracker Team
# @version 1.0
# @since 2024

# YAML 언어 서버를 위한 스키마 참조
# yaml-language-server: $schema=./application-schema.json

spring:
  # 데이터베이스 연결 설정
  datasource:
    # MariaDB 데이터베이스 연결 URL
    url: jdbc:mariadb://localhost:3306/health_routine
    # 데이터베이스 사용자명 (개발 환경용)
    username: root        # ← 네 DB 사용자명
    # 데이터베이스 비밀번호 (개발 환경용)
    password: 123456789        # ← 네 DB 비밀번호
    # MariaDB JDBC 드라이버 클래스명
    driver-class-name: org.mariadb.jdbc.Driver

  # JPA/Hibernate 설정
  jpa:
    hibernate:
      # DDL 자동 생성 모드: validate (스키마 검증만 수행)
      ddl-auto: validate
    properties:
      # SQL 쿼리 포맷팅 활성화 (개발 시 가독성 향상)
      "[hibernate.format_sql]": true
      # 데이터베이스 시간대 설정 (한국 표준시)
      "[hibernate.jdbc.time_zone]": Asia/Seoul

  # Jackson JSON 직렬화 설정
  jackson:
    # JSON 직렬화 시 사용할 시간대 (한국 표준시)
    time-zone: Asia/Seoul
    
  # Spring Security 기본 설정 (개발용)
  security:
     user:
      # 기본 인증 사용자명 (개발 환경용)
      name: user             # ← dev용 아이디
      # 기본 인증 비밀번호 (개발 환경용)
      password: pass1234     # ← dev용 비번

# CORS (Cross-Origin Resource Sharing) 설정
cors:
  # 허용할 프론트엔드 도메인 목록
  allowed-origins: http://localhost:5173,http://127.0.0.1:5173

# 서버 설정
server:
  # 서버 포트 번호
  port: 8081
  servlet:
    # 애플리케이션 컨텍스트 경로
    context-path: /v1

# JWT (JSON Web Token) 설정
jwt:
  # JWT 서명에 사용할 비밀키 (환경변수 또는 기본값 사용)
  secret: ${HRT_JWT_SECRET:dev-secret-change-me-should-be-at-least-32-bytes-1234567890abcd}
  # 액세스 토큰 만료 시간 (분 단위)
  access-exp-minutes: 30

# Spring Boot Actuator 모니터링 설정
management:
  endpoints:
    web:
      exposure:
        # 노출할 모니터링 엔드포인트 목록
        include: health,info,metrics,httpexchanges
  endpoint:
    health:
      # 헬스 체크 상세 정보 표시 조건 (인증된 사용자에게만)
      show-details: when-authorized

# SpringDoc OpenAPI/Swagger 설정
springdoc:
  api-docs:
    # API 문서 생성 활성화
    enabled: true
  swagger-ui:
    # Swagger UI 접근 경로
    path: /swagger-ui.html

# 외부 LLM(OpenAI 등) 연동 설정 및 AI 기능 토글
openai:
  api:
    # 환경변수에서 읽어오며, 기본값은 빈 값으로 둠(키 없어도 애플리케이션이 기동되도록)
    key: ${OPENAI_API_KEY:}
    url: https://api.openai.com/v1/chat/completions
    model: ${OPENAI_MODEL:gpt-3.5-turbo}
    timeout-ms: ${OPENAI_TIMEOUT_MS:10000}

ai:
  # 기본 비활성화. 키를 넣고 활성화할 때 true로 변경하거나, 환경변수 AI_ENABLED=true 설정
  enabled: ${AI_ENABLED:false}

