spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/health_routine
    username: root        # ← 네 DB 사용자명
    password: 123456789        # ← 네 DB 비밀번호
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.jdbc.time_zone]": Asia/Seoul

  jackson:
    time-zone: Asia/Seoul
  security:
     user:
      name: user             # ← dev용 아이디
      password: pass1234     # ← dev용 비번
server:
  port: 8080
  servlet:
    context-path: /v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,httpexchanges
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

