CREATE TABLE IF NOT EXISTS comments (
  comment_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  routine_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  content VARCHAR(2000) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_comments_routine (routine_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
