server:
  port: 8081

spring:
  application:
    name: auth-service
  
  datasource:
    url: jdbc:mariadb://localhost:3306/health_routine_tracker
    username: hrt_user
    password: hrt_password
    driver-class-name: org.mariadb.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  security:
    user:
      name: admin
      password: admin

# JWT ?¤ì •
jwt:
  secret: ${JWT_SECRET:change-me-please-use-32-bytes-minimum-xxxxxxxxxxxxxxxx}
  access-token-validity: 3600000  # 1?œê°„ (ë°€ë¦¬ì´ˆ)
  refresh-token-validity: 604800000  # 7??(ë°€ë¦¬ì´ˆ)

# Eureka Client ?¤ì •
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Actuator ?¤ì •
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.hrt.auth: DEBUG
    org.springframework.security: DEBUG


