name: deploy-prod

on:
  push:
    branches: [ main ]
    paths:
      - 'health-routine-tracker/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rsync sources to EC2
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avz --delete
          path: ./
          remote_path: ${{ secrets.EC2_WORKDIR }}
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ${{ secrets.EC2_USER }}
          remote_key: ${{ secrets.EC2_KEY }}

      - name: Deploy on EC2 (docker compose up -d)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -euo pipefail
            cd "$EC2_WORKDIR/health-routine-tracker"
            # Load env if present
            if [ -f .env ]; then echo "Loaded .env"; fi
            docker compose -f docker-compose-prod.yml up -d --build
            docker compose -f docker-compose-prod.yml ps

